# Generated by Django 5.2.17 on 2026-09-30 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0002_alter_knowledgechunk_id_alter_project_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('SKIPPED', 'Skipped'), ('DONE', 'Done'), ('FAILED', 'Failed'), ('EXPIRED', 'Expired')], db_index=True, default='QUEUED', max_length=30)),
                ('task_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('target_sha', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('force', models.BooleanField(default=False)),
                ('lease_expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('result_json', models.JSONField(default=dict)),
                ('error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_runs', to='knowledge.syncjob')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_runs', to='knowledge.project')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('job', 'project'), name='uq_sync_run_job_project'), models.UniqueConstraint(condition=models.Q(('status__in', ['QUEUED', 'RUNNING'])), fields=('project',), name='uq_active_project_sync'), models.CheckConstraint(condition=models.Q(models.Q(('status__in', ['QUEUED', 'RUNNING']), _negated=True), ('lease_expires_at__isnull', False), _connector='OR'), name='ck_active_sync_has_lease')],
            },
        ),
    ]
