# Generated by Django 5.2.17 on 2026-09-30 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0003_projectsyncrun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syncjob',
            name='requested_by',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='syncjob',
            name='status',
            field=models.CharField(choices=[('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('DONE', 'Done'), ('PARTIAL', 'Partial'), ('FAILED', 'Failed')], db_index=True, default='QUEUED', max_length=30),
        ),
        migrations.AddConstraint(
            model_name='syncjob',
            constraint=models.UniqueConstraint(condition=models.Q(('requested_by', 'celery-beat'), ('status__in', ['QUEUED', 'RUNNING'])), fields=('requested_by',), name='uq_active_scheduled_sync_job'),
        ),
    ]
