from abc import ABC,abstractmethod
class SourceControlProvider(ABC):
 @abstractmethod
 async def repository(self,full_name): ...
 @abstractmethod
 async def repositories(self): ...
 @abstractmethod
 async def branch(self,full_name,branch): ...
 @abstractmethod
 async def repository_tree(self,full_name,tree_sha): ...
 @abstractmethod
 async def raw_file(self,full_name,file_path,ref): ...
 @abstractmethod
 async def issues(self,full_name,updated_after=None): ...
 @abstractmethod
 async def merge_requests(self,full_name): ...
